FROM node:18-alpine AS build

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build

COPY src/credentials.json /app/dist/credentials.json

EXPOSE 8000

FROM node:18-alpine AS production

WORKDIR /app

COPY --from=build /app/package*.json ./

RUN npm install --only=production

COPY --from=build /app/dist ./dist

CMD ["node", "dist/index.js"]
